version: 2.1
commands:
  bundle_install_and_test:
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake compile
      - run: bundle exec rspec

jobs:
  test-ruby-263:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - bundle_install_and_test
  test-ruby-271:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - bundle_install_and_test

workflows:
  rc:
    jobs:
      - test-ruby-263
      - test-ruby-271

